### PR TITLE
Closes #65 - Fix sell sub-commands

### LINKED ISSUE #65: `/sell argument confirm` does not work
**Describe the bug**
the `hand` & `inventory confirm` sub commands do exist.

**To Reproduce**

1. Type '/sell hand/inventory confirm'
2. See error

### PR DESCRIPTION
**Pull request by ZachyFoxx**

### CODE REVIEW

File: bukkit/src/main/kotlin/commands/SellCommand.kt [hunk 1]
```diff
@@ -18,21 +18,39 @@ import kotlin.math.roundToInt
 import org.bukkit.Bukkit
 import org.bukkit.entity.Player
 
+// Well... this is a little messy...
+// TODO: Clean this up
```
Comment (alyx) [inline bukkit/src/main/kotlin/commands/SellCommand.kt:22]: Well, this is a little messy.

**Review by alyx — APPROVED** [review]
lgtm
